// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20250826171329_ConstraintsDeTamanho")]
    partial class ConstraintsDeTamanho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuncionarioRecurso", b =>
                {
                    b.Property<long>("FuncionariosId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecursosAlocadosId")
                        .HasColumnType("bigint");

                    b.HasKey("FuncionariosId", "RecursosAlocadosId");

                    b.HasIndex("RecursosAlocadosId");

                    b.ToTable("FuncionarioRecurso");
                });

            modelBuilder.Entity("src.Domain.Model.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<long>("Matricula")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("src.Domain.Model.Interface.Recurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Recurso", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("src.Domain.Model.Laboratorio", b =>
                {
                    b.HasBaseType("src.Domain.Model.Interface.Recurso");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QComp")
                        .HasColumnType("int");

                    b.ToTable("Laboratorio", (string)null);
                });

            modelBuilder.Entity("src.Domain.Model.Notebook", b =>
                {
                    b.HasBaseType("src.Domain.Model.Interface.Recurso");

                    b.Property<DateTime>("DAquisicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("src.Domain.Model.Sala", b =>
                {
                    b.HasBaseType("src.Domain.Model.Interface.Recurso");

                    b.Property<int>("Lugares")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("TemProjetor")
                        .HasColumnType("bit");

                    b.ToTable("Sala", (string)null);
                });

            modelBuilder.Entity("FuncionarioRecurso", b =>
                {
                    b.HasOne("src.Domain.Model.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Domain.Model.Interface.Recurso", null)
                        .WithMany()
                        .HasForeignKey("RecursosAlocadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Domain.Model.Laboratorio", b =>
                {
                    b.HasOne("src.Domain.Model.Interface.Recurso", null)
                        .WithOne()
                        .HasForeignKey("src.Domain.Model.Laboratorio", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Domain.Model.Notebook", b =>
                {
                    b.HasOne("src.Domain.Model.Interface.Recurso", null)
                        .WithOne()
                        .HasForeignKey("src.Domain.Model.Notebook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Domain.Model.Sala", b =>
                {
                    b.HasOne("src.Domain.Model.Interface.Recurso", null)
                        .WithOne()
                        .HasForeignKey("src.Domain.Model.Sala", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
