// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20250826163722_RelacoesFuncionariosRecursos")]
    partial class RelacoesFuncionariosRecursos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuncionarioRecurso", b =>
                {
                    b.Property<long>("FuncionariosId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecursosAlocadosId")
                        .HasColumnType("bigint");

                    b.HasKey("FuncionariosId", "RecursosAlocadosId");

                    b.HasIndex("RecursosAlocadosId");

                    b.ToTable("FuncionarioRecurso");
                });

            modelBuilder.Entity("src.Domain.Model.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<long>("Matricula")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("src.Domain.Model.Interface.Recurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Recurso");

                    b.HasDiscriminator().HasValue("Recurso");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("src.Domain.Model.Laboratorio", b =>
                {
                    b.HasBaseType("src.Domain.Model.Interface.Recurso");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QComp")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Laboratorio");
                });

            modelBuilder.Entity("src.Domain.Model.Notebook", b =>
                {
                    b.HasBaseType("src.Domain.Model.Interface.Recurso");

                    b.Property<DateTime>("DAquisicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Recurso", t =>
                        {
                            t.Property("Descricao")
                                .HasColumnName("Notebook_Descricao");
                        });

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("src.Domain.Model.Sala", b =>
                {
                    b.HasBaseType("src.Domain.Model.Interface.Recurso");

                    b.Property<int>("Lugares")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("TemProjetor")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Sala");
                });

            modelBuilder.Entity("FuncionarioRecurso", b =>
                {
                    b.HasOne("src.Domain.Model.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Domain.Model.Interface.Recurso", null)
                        .WithMany()
                        .HasForeignKey("RecursosAlocadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
